### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by coolicer** [axetroy/webuild#11]
[95643]: start.
ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/xxx/xxx/wxapp/dist"
    at /usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/transformation/pipeline.js:46:16)
    at /usr/local/lib/node_modules/@axetroy/webuild/node_modules/.6.26.0@babel-core/lib/api/node.js:134:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

最后又出现 了这样的情况
<img width="685" alt="qq20180201-143445 2x" src="https://user-images.githubusercontent.com/811078/35664458-231a4a70-075d-11e8-99a4-1a18bb2d36ab.png">

**Comment by coolicer** [comment]
https://github.com/future-memory/qczwxapp
这是我同事写的，我怀疑是一个page文件夹有几个.js导致？

**Comment by axetroy** [comment]
抱歉，出差中，暂时无法解决你的问题.
如果有疑问，可以参考demo，自己写的，还有官方原生的demo。

**Comment by axetroy** [comment]
@coolicer 
看了下源码，你得把原本的小程序代码，放在src目录。

不支持package.json和小程序源码放在同一目录

请参考本项目的examples

**Comment by coolicer** [comment]
@axetroy 整个项目放在src吗？

**Comment by axetroy** [comment]
@coolicer 
对的

**Comment by coolicer** [comment]
@axetroy 好的，谢谢
